# Generated by Django 5.1.7 on 2025-03-23 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questAns', '0002_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='questAns.question'),
        ),
    ]
