# Generated by Django 5.1.7 on 2025-03-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questAns', '0003_alter_reply_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='questioner',
            new_name='answerer',
        ),
    ]
