# Generated by Django 5.1.7 on 2025-03-28 15:11

from django.db import migrations, models
from django.utils.timezone import now # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('questAns', '0006_remove_question_time_remove_question_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
