# Generated by Django 5.1.7 on 2025-03-28 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questAns', '0010_remove_question_time_remove_question_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
