# Generated by Django 5.1.7 on 2025-03-28 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questAns', '0011_reply_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
