# Generated by Django 5.1.7 on 2025-03-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questAns', '0012_question_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='time',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='time',
        ),
    ]
