# Generated by Django 5.1.7 on 2025-03-28 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questAns', '0013_remove_question_time_remove_reply_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
