# Generated by Django 5.1.7 on 2025-03-28 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questAns', '0015_alter_question_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
